

export const WISHLIST_ACTION_TYPES = {
    WISHLIST_ITEM_LOAD_REQUEST: "WISHLIST_ITEM_LOAD_REQUEST",
    WISHLIST_ITEM_LOAD_SUCCESS: "WISHLIST_ITEM_LOAD_SUCCESS",
    WISHLIST_ITEM_LOAD_FAILURE: "WISHLIST_ITEM_LOAD_FAILURE",
    
    ADD_ITEM_TO_WISHLIST_REQUEST: "ADD_ITEM_TO_WISHLIST_REQUEST",
    ADD_ITEM_TO_WISHLIST_SUCCESS: "ADD_ITEM_TO_WISHLIST_SUCCESS",
    ADD_ITEM_TO_WISHLIST_FAILURE: "ADD_ITEM_TO_WISHLIST_FAILURE",

    UPDATE_ITEM_OF_WISHLIST_REQUEST: "UPDATE_ITEM_OF_WISHLIST_REQUEST",
    UPDATE_ITEM_OF_WISHLIST_SUCCESS: "UPDATE_ITEM_OF_WISHLIST_SUCCESS",
    UPDATE_ITEM_OF_WISHLIST_FAILURE: "UPDATE_ITEM_OF_WISHLIST_FAILURE",

    DELETE_ITEM_FROM_WISHLIST_REQUEST: "DELETE_ITEM_FROM_WISHLIST_REQUEST",
    DELETE_ITEM_FROM_WISHLIST_SUCCESS: "DELETE_ITEM_FROM_WISHLIST_SUCCESS",
    DELETE_ITEM_FROM_WISHLIST_FAILURE: "DELETE_ITEM_FROM_WISHLIST_FAILURE",

    CLEAR_WISHLIST_SUCCESS: "CLEAR_WISHLIST_SUCCESS",
    CLEAR_WISHLIST_FAILURE: "CLEAR_WISHLIST_FAILURE"
};